# Folosim imaginea de Apache
FROM httpd:alpine

# Copiem fișierul index.html în directorul specificat pentru Apache
COPY index.html /usr/local/apache2/htdocs/index.html

# Expunem portul 80 pentru a accesa aplicația
EXPOSE 80
