# Folosim imaginea Nginx de bază
FROM nginx:alpine

# Copiază fișierele din directorul local în directorul public al Nginx
COPY ./frontend /usr/share/nginx/html

# Expune portul 80 pentru a accesa aplicația
EXPOSE 80
